### ISSUE TITLE
Secp256r1 

### ISSUE THREAD

**Issue by hgedia** [MinaFoundation/ecosystem-ideas#2]
## Summary

Enabling transactions to be signed and verified using the [secp256r1](https://secg.org/sec2-v2.pdf) curve enhances the end-user experience significantly. This approach allows transactions to be signed using biometrics such as fingerprints, FaceIDs, and others. It also supports moving away from seed phrases, offering improved security through security chips in devices like Apple’s [Secure Enclave](https://support.apple.com/guide/security/secure-enclave-sec59b0b31ff/web) and Android's [Secure Element](https://developer.android.com/privacy-and-security/keystore). 

Implementation involves creating a new curve using the secp256r1 parameters and implementing an ECDSA signing algorithm. A working demo can be made using passkey signing.

Submitted by [d0x471b](https://github.com/0x471)

## Resources
- Foreign field arithmetic - [docs](https://docs.minaprotocol.com/zkapps/o1js/foreign-fields) , [video](https://www.youtube.com/watch?v=IBeo5epQoYo) from ZK9.
- [Foreign elliptic curves](https://docs.minaprotocol.com/zkapps/o1js-reference/classes/ForeignCurve)
- [ECDSA implementation](https://docs.minaprotocol.com/zkapps/o1js/ecdsa) using the secp256k1 curve 

## Ready to build?
Please read the docs on how to [progress](https://github.com/MinaFoundation/ecosystem-ideas?tab=readme-ov-file#claim).

**Comment by YashBit** [comment]
@hgedia Taking a look at this right now. Seems quite interesting, will send in a proposal soon. I have experience implementing some encryption algorithms as well.

**Comment by YashBit** [comment]
@hgedia Done some background research. Is there a senior engineer you could connect me to?

**Comment by hgedia** [comment]
@YashBit  - let us sync on this offline.

**Comment by hgedia** [comment]
This is about to be merged : https://github.com/o1-labs/o1js/pull/1885
